<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\PowerSaver\PowerDrainMath.cs" Link="PowerDrainMath.cs" />
    <Compile Include="..\PowerSaver\PowerSaverConfigMigration.cs" Link="PowerSaverConfigMigration.cs" />
  </ItemGroup>

</Project>
